// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"DevToolsManage","status":true,"description":"開発支援プラグイン","parameters":{"StartupDevTool":"true","ShortcutList":"","ShowFPS":"OFF","CutTitle":"1","RapidStart":"false","RapidSpeed":"2","SlowSpeed":"2","InvalidMessageSkip":"false","MenuBarVisible":"true","ClickMenu":"-1","OutputStartupInfo":"false","StartupOnTop":"false","UseReloadData":"false","UseBreakPoint":"false"}},
{"name":"EventLabel","status":true,"description":"イベントラベルプラグイン","parameters":{"showDefault":"false","hideNoImage":"true","hideNameEv":"true","fontSize":"16","backColor":"rgba(0,0,0,0.5)","padding":"2","showTail":"false","tailWidth":"12","tailHeight":"8","invisibleSwitchId":"0"}},
{"name":"NRP_PicturePriority","status":true,"description":"v1.021 ピクチャ毎に表示優先度を変更します。","parameters":{"DefaultZ":"","ReleaseOnTransfer":"false"}},
{"name":"OKAS_SaveChangeParallax","status":true,"description":"遠景の保存、復元、予約","parameters":{"Save Parallax Variable":"2","Set Parallax Variable":"3","Reset Permission":"false"}},
{"name":"OKAS_SaveChangeTint","status":true,"description":"色調の保存、復元、予約","parameters":{"Save Tint Variable":"4","Set Tint Variable":"5"}},
{"name":"OKAS_CustomCommand","status":true,"description":"変数代入＆コモンイベント実行をワンコマンド化","parameters":{"ThisV":"6","EventV":"7","TargetV":"8","StagingV":"9","PictV":"10","MovieV":"11","MapBGM":"12"}},
{"name":"OKAS_consolelog","status":true,"description":"console.logの入力、管理支援","parameters":{"logSwitch":"1","tableVariable1":"1","tableVariable2":"14","tableVariable3":"15","tableVariable4":"16","tableVariable5":"17","tableVariable1Name":"会話回数","tableVariable2Name":"2列目","tableVariable3Name":"3列目","tableVariable4Name":"4列目","tableVariable5Name":"5列目"}}
];
